import React, { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../Components";
const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  } else {
    return (
      <h2 className={"mt-5 font-bold text-[#6449ff] text-xl uppercase"}>
        {title}
      </h2>
    );
  }
};
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [AllPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");
  const [searchedResults, setSearchedResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      try {
        const response = await fetch(
          "https://aimage-l1za.onrender.com/api/v1/post",
          {
            method: "GET",
            headers: {
              "Content-Type": "application/json",
            },
          }
        );
        if (response.ok) {
          const result = await response.json();
          console.log("WE good!");
          setAllPosts(result.data.reverse());
        }
      } catch (e) {
        console.log("we are here Not good !!");
        alert(e);
      } finally {
        setLoading(false);
      }
    };
    fetchPosts().then(() => console.log("done"));
  }, []);
  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);
    setSearchTimeout((prev) => {
      setTimeout(() => {
        const searchResults = AllPosts.filter(
          (post) =>
            post.name.toLowerCase().includes(searchText.toLowerCase()) ||
            post.prompt.toLowerCase().includes(searchText.toLowerCase())
        );
        setSearchedResults(searchResults);
      }, 500);
    });
  };
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className={"font-extrabold text-[#22328] text-[32px]"}>
          The Community ShowCase
        </h1>
        <p className={"mt-2 text-[#666e75] text-[24px] max-w-[500px]"}>
          Browse through a collection of images from the community,generated by
          AI.
        </p>
      </div>
      <div className="mt-16">
        <FormField
          labelName={"Search posts"}
          type={"text"}
          name={"text"}
          placeholder={"Search posts"}
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className={"font-medium text-[#666e75] text-xl mb-3"}>
                Showing results for{" "}
                <span className={"text=[#22328]"}>{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-2 md:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No Search results found."
                />
              ) : (
                <RenderCards data={AllPosts} title={"No posts found"} />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
